USE week09;
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (22, 'Dustin', 7, 45);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (29, 'Brutus', 1, 33);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (31, 'Lubber', 8, 55.5);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (32, 'Andy', 8, 25.5);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (58, 'Rusty', 10, 35);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (64, 'Horatio', 7, 35);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (71, 'Zorba', 10, 16);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (74, 'Horatio', 9, 35);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (85, 'Art', 3, 25.5);
INSERT INTO sailors_1 (sid, sname, rating, age) VALUES (95, 'Bob', 3, 63.5);
