USE week08;
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q01s1','Introduction');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q01s2','Introduction');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q02s1','System of linear equations');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q02s2','System of linear equations');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q03s1','Vector spaces');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q03s2','Vector spaces');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q04s1','Linear transformations');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q04s2','Linear transformations');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q05s1','Inner-product spaces');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q05s2','Inner-product spaces');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q06s1','Ortho-normal basis');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q06s2','Ortho-normal basis');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q07s1','Eigenvalues and eigenvectors');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q07s2','Eigenvalues and eigenvectors');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q08s1','Hermitian symmetric matrices');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q08s2','Hermitian symmetric matrices');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q09s1','Positive definite matrices');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q09s2','Positive definite matrices');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q10s1','QR factorization');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q11s2','Change of basis and similarity');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q11s1','Change of basis and similarity');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q12s2','Diagonalization');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q12s1','Diagonalization');
INSERT INTO concept (cid, qn, description) VALUES ('DA105', 'q10s2','QR factorization');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q01s1','Overview of Data Science');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q01s2','Overview of Data Science');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q02s1','Data collection and management');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q02s2','Data collection and management');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q03s1','Multimodal data');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q03s2','Multimodal data');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q04s1','Data collection and curation');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q04s2','Data collection and curation');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q05s1','XML and JSON formats');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q05s2','XML and JSON formats');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q06s1','Basics of SQL');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q06s2','Basics of SQL');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q07s1','Data cleaning');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q07s2','Data cleaning');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q08s1','Plots');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q08s2','Plots');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q09s1','Reading and exporting data');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q09s2','Reading and exporting data');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q10s1','Exploratory data analysis');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q10s2','Exploratory data analysis');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q11s1','Outlier detection');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q11s2','Outlier detection');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q12s1','Linear regression and Bayes classifier');
INSERT INTO concept (cid, qn, description) VALUES ('DA106', 'q12s2','Linear regression and Bayes classifier');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q01s1','Introduction');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q01s2','Introduction');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q02s1','OS');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q02s2','OS');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q03s1','Booting');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q03s2','Booting');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q04s1','Basic Commands - 1');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q04s2','Basic Commands - 1');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q05s1','Basic Commands - 2');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q05s2','Basic Commands - 2');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q06s1','Basics of Shell - 1');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q06s2','Basics of Shell - 1');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q07s1','Basics of Shell - 2');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q07s2','Basics of Shell - 2');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q08s1','Basics of Shell - 3');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q08s2','Basics of Shell - 3');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q09s1','Package management');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q09s2','Package management');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q10s1','User management');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q10s2','User management');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q11s1','File systems');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q11s2','File systems');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q12s1','System configuration and device drivers');
INSERT INTO concept (cid, qn, description) VALUES ('DA107', 'q12s2','System configuration and device drivers');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q01s1','Fundamental concepts');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q01s2','Fundamental concepts');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q02s1','Conditional statements');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q02s2','Conditional statements');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q03s1','Loops');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q03s2','Loops');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q04s1','Data structures: Lists');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q04s2','Data structures: Lists');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q05s1','Data structures: Dictionaries');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q05s2','Data structures: Dictionaries');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q06s1','Data structures: Sets');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q06s2','Data structures: Sets');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q07s1','Data structures: Use cases');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q07s2','Data structures: Use cases');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q08s1','Functions: Procedural');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q08s2','Functions: Procedural');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q09s1','Functions: Recursive');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q09s2','Functions: Recursive');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q10s1','Classes');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q10s2','Classes');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q11s1','Exception handling');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q11s2','Exception handling');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q12s1','File handling');
INSERT INTO concept (cid, qn, description) VALUES ('DA108', 'q12s2','File handling');
